### ISSUE TITLE
onDisconnect() function declared in Firebase 😑

### ISSUE THREAD

**Issue by aifeelit** [aifeelit/firebase-presence-detect#1]
It detects users connection and make it online/offline.
Whenever the connection is disconnected then this even is called.
When close tab, browser, bad internet connection whatever reason.
But it works also when REFRESH the browser.
I'd like to make it not work when refresh.
Any solution would be appreciated. 😍

**Comment by millucas** [comment]
i think its impossible

**Comment by millucas** [comment]
its server side function, you can't implement it on frontend side

**Comment by edrdm** [comment]
seems interesting...
possible i think though
